<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('event_bookings', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('event_id')->nullable(); // Link to an events table if it exists, otherwise just store name
            $table->string('event_name'); // Storing event name directly as per current frontend structure
            $table->string('first_name');
            $table->string('last_name');
            $table->string('email');
            $table->string('phone'); // Phone numbers are unique for referral retrieval
            $table->string('how_heard')->nullable();
            $table->string('inviter_name')->nullable(); // Name of the person who invited this registrant
            $table->string('inviter_phone')->nullable(); // Phone of the person who invited this registrant
            $table->string('referral_code')->unique(); // Unique code generated by the server for this registrant
            $table->string('referred_by_code')->nullable(); // Stores the referral_code of the inviter
            $table->foreign('event_id')
                ->references('id')->on('events')
                ->onDelete('set null');
            $table->unique(['event_id', 'phone']);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('event_bookings');
    }
};
